services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2_db
    platform: linux/amd64
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      H2_OPTIONS: "-tcpPort 9092 -webPort 8082 -tcpAllowOthers -ifNotExists -tcp"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8082" ]
      interval: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - h2-database
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
